D:/_devs/Python01/gitdev/dsa2/
os.getcwd D:\_devs\Python01\gitdev\dsa2
D:/_devs/Python01/gitdev/dsa2/
D:\_devs\Python01\gitdev\dsa2
D:/_devs/Python01/gitdev/dsa2/
D:/_devs/Python01/gitdev/dsa2/data/
{'config_name': 'multi_lightgbm', 'model_name': 'LGBMClassifier', 'path_config_model': 'D:/_devs/Python01/gitdev/dsa2//multi_classifier.py', 'path_model': 'data/output/multiclass/a01_LGBMClassifier/', 'path_data_train': 'data/input/multiclass/train/', 'path_data_test': 'data/input/multiclass/test/', 'path_output_pred': '/data/output/multiclass/pred_a01_multi_lightgbm/', 'n_sample': 6000}
D:/_devs/Python01/gitdev/dsa2/

  ('D:/_devs/Python01/gitdev/dsa2/data/input/multiclass/test//features.zip', 'D:/_devs/Python01/gitdev/dsa2/data/output/multiclass/a01_LGBMClassifier/', 'D:/_devs/Python01/gitdev/dsa2//data/output/multiclass/pred_a01_multi_lightgbm/') 

  ('loading', 'pet_id', 'D:/_devs/Python01/gitdev/dsa2/data/input/multiclass/test//features.zip') 
['D:/_devs/Python01/gitdev/dsa2/data/input/multiclass/test\\features.zip']

  ('dfX_raw',                              0  ...              8071
pet_id              ANSL_75005  ...        ANSL_69436
issue_date    17-08-2005 00:00  ...  02-02-2016 00:00
listing_date  07-09-2017 15:35  ...  28-02-2017 16:47
condition                    0  ...                 0

[4 rows x 8072 columns]) 

  ('dfy not loaded', None, TypeError('expected str, bytes or os.PathLike object, not NoneType',)) 

  ('--------------pipe_ist-----------------', [{'uri': 'source/preprocessors.py::pd_colnum_bin', 'pars': {}, 'cols_family': 'colnum', 'cols_out': 'dfnum_bin', 'type': ''}, {'uri': 'source/preprocessors.py::pd_colnum_binto_onehot', 'pars': {}, 'cols_family': 'colnum', 'cols_out': 'dfnum_onehot', 'type': ''}, {'uri': 'source/preprocessors.py::pd_colcat_bin', 'pars': {}, 'cols_family': 'colcat', 'cols_out': 'dfcat_bin', 'type': ''}, {'uri': 'source/preprocessors.py::pd_colcat_to_onehot', 'pars': {}, 'cols_family': 'colcat', 'cols_out': 'dfcat_onehot', 'type': ''}, {'uri': 'source/preprocessors.py::pd_colcross', 'pars': {}, 'cols_family': 'colcross', 'cols_out': 'dfcross_hot', 'type': 'cross'}]) 

  ('########### Load column by column type ##################################',) 

  ({'coly': 'pet_category', 'colid': 'pet_id', 'colcat': ['color_type', 'condition'], 'colnum': ['length(m)', 'height(cm)', 'X1', 'X2', 'breed_category'], 'coltext': [], 'coldate': [], 'colcross': ['condition', 'color_type', 'length(m)', 'height(cm)', 'X1', 'X2', 'breed_category']},) 

  ('###################', {'uri': 'source/preprocessors.py::pd_colnum_bin', 'pars': {}, 'cols_family': 'colnum', 'cols_out': 'dfnum_bin', 'type': ''}, '#######################################################') 

  ('D:\\_devs\\Python01\\gitdev\\dsa2',) 
D:/_devs/Python01/gitdev/dsa2/
Traceback (most recent call last):
  File "multi_classifier.py", line 272, in <module>
    fire.Fire()
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\fire\core.py", line 468, in _Fire
    target=component.__name__)
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "multi_classifier.py", line 247, in predict
    n_sample    = nsample if nsample is not None else m['n_sample'])
  File "D:\_devs\Python01\gitdev\dsa2\source\run_inference2.py", line 107, in run_predict
    dfX, cols_family = preprocess(df, path_pipeline, preprocess_pars={'cols_group':cols_group})
  File "D:\_devs\Python01\gitdev\dsa2\source\run_preprocess2.py", line 304, in preprocess_inference
    df_       = df[ cols_list]
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\pandas\core\frame.py", line 3001, in __getitem__
    indexer = self.loc._convert_to_indexer(key, axis=1, raise_missing=True)
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\pandas\core\indexing.py", line 1285, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\pandas\core\indexing.py", line 1092, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\pandas\core\indexing.py", line 1185, in _validate_read_indexer
    raise KeyError("{} not in index".format(not_found))
KeyError: "['breed_category'] not in index"
